export const d54 = [
  { id: 1, sentence: "Мальчик с полчаса поделал уроки и побежал гулять.", ans: "поделал — làm (bài tập) một lúc ngắn rồi thôi", viet: "Cậu bé làm bài tập khoảng nửa tiếng rồi chạy đi chơi.", why: "СВ поделать = làm trong thời gian ngắn. Thường hàm ý làm không nghiêm túc, chưa xong đã dừng." },
  { id: 2, sentence: "Мы проделали большую и трудную работу.", ans: "проделали — đã thực hiện/hoàn thành (một khối lượng công việc lớn), nghĩa 2", viet: "Chúng tôi đã thực hiện một khối lượng công việc lớn và khó khăn.", why: "СВ проделать работу = thực hiện xong một công việc (nhấn mạnh khối lượng hoàn thành). Trang trọng hơn сделали работу." },
  { id: 3, sentence: "Что ты наделал!", ans: "наделал — đã gây ra bao nhiêu chuyện! (nghĩa: произвести много — ở đây là rắc rối)", viet: "Cậu đã gây ra chuyện gì thế này!", why: "Biểu thức cảm thán. Наделать thường đi với тân ngữ tiêu cực: наделать ошибок, наделать хлопот. Tương đương \"Anh/em làm gì vậy trời ơi!\"" },
  { id: 4, sentence: "Эту работу надо переделать.", ans: "переделать — làm lại (nghĩa 1: заново или по-иному)", viet: "Công việc này cần phải làm lại.", why: "СВ переделать = làm lại từ đầu hoặc theo cách khác. Khác với доделать (hoàn thành nốt phần còn lại)." },
  { id: 5, sentence: "Ничего не поделаешь, надо идти на работу!", ans: "не поделаешь — chẳng làm được gì (thành ngữ: vô phương, đành chịu)", viet: "Chẳng làm gì được đâu, phải đi làm thôi!", why: "Ничего не поделаешь = thành ngữ cố định, nghĩa \"không thể làm gì khác được, đành chấp nhận\". Tương đương \"Biết làm sao bây giờ!\"" },
  { id: 6, sentence: "Пойду спать, а реферат завтра доделаю.", ans: "доделаю — sẽ hoàn thành nốt (bài) vào ngày mai", viet: "Tôi đi ngủ đây, còn bài tiểu luận mai tôi sẽ làm nốt.", why: "СВ доделать (чаще СВ) = làm xong phần còn lại. Luôn hàm ý công việc đang dang dở." },
  { id: 7, sentence: "Завтра выходной! Ничего не буду делать!", ans: "делать — làm (bất cứ việc gì), НСВ tổng quát", viet: "Mai là ngày nghỉ! Tôi sẽ không làm gì cả!", why: "НСВ делать trong phủ định tổng quát. Không thể thay bằng СВ сделать ở đây vì nói về thói quen/kế hoạch chứ không phải hành động cụ thể." },
  { id: 8, sentence: "Он сделал большую ошибку, когда бросил университет.", ans: "сделал — đã phạm (một lỗi lớn), nghĩa 4: совершать", viet: "Anh ấy đã phạm một sai lầm lớn khi bỏ đại học.", why: "Сделать ошибку = phạm lỗi. Cụm cố định quan trọng. СВ nhấn mạnh hành động đã xảy ra và hoàn thành." },
  { id: 9, sentence: "Надо вызвать мастера: пусть заделает щель в двери hoặc поменяет дверь.", ans: "заделает — trám/bịt kín khe hở", viet: "Cần gọi thợ: để họ bịt khe hở ở cửa hoặc thay cửa.", why: "СВ заделает щель = bịt kín, trám đầy kẽ hở. Cụm thông dụng trong sửa chữa nhà cửa." },
  { id: 10, sentence: "Не говори глупости! Не надо делать из меня идиота!", ans: "делать из меня идиота — biến tôi thành kẻ ngốc (nghĩa 5: превращать)", viet: "Đừng nói ngớ ngẩn! Đừng có biến tôi thành thằng ngốc!", why: "Делать из кого-либо кого-либо = biến ai thành ai. Cấu trúc: делать из + Р.п. + В.п. Thường dùng trong câu phản đối." },
  { id: 11, sentence: "Всех дел не переделаешь!", ans: "не переделаешь — không thể làm hết mọi việc (nghĩa 2: много)", viet: "Mọi việc trên đời không bao giờ làm hết được đâu!", why: "Thành ngữ dân gian: Всех дел не переделаешь = Không ai có thể làm hết việc trên đời. Lời khuyên đừng quá cố." },
  { id: 12, sentence: "Ребята проделали дыру в заборе.", ans: "проделали — đục/khoét một lỗ trên hàng rào (nghĩa 1: сделать отверстие)", viet: "Các bạn nhỏ đã đục một cái lỗ trên hàng rào.", why: "СВ проделать дыру/отверстие = khoét/đục lỗ. Nghĩa 1 cụ thể, vật lý." },
];

export const d55 = [
  { id: 1, sentence: "Эта статья в газете наделала много шума.", ans: "наделала — gây ra nhiều tiếng ồn/xôn xao (dư luận)", viet: "Bài báo này trên tờ báo đã gây ra nhiều tiếng vang (xôn xao).", why: "Наделать шума = gây xôn xao, làm dư luận ồn ào. Cụm cố định, nghĩa bóng." },
  { id: 2, sentence: "У корзинки оторвалась ручка, но ребята её приделали.", ans: "приделали — gắn lại, lắp lại (tay cầm)", viet: "Cái giỏ bị đứt tay cầm, nhưng các bạn nhỏ đã gắn lại nó.", why: "СВ приделала = gắn chặt, lắp cố định vào vật khác." },
  { id: 3, sentence: "Она сделала его несчастным на всю жизнь!", ans: "сделала — biến anh ấy thành người bất hạnh (nghĩa 5: превращать)", viet: "Cô ấy đã làm anh ấy bất hạnh suốt cả cuộc đời!", why: "Сделать кого-либо + Т.п. (несчастным, счастливым…) = làm cho ai trở thành như thế nào." },
  { id: 4, sentence: "Этот портфель служит мне много лет — и всё как новенький! Ему ничего не делается!", ans: "не делается — chẳng hề hấn gì, không sao cả (вô nhân xưng, nghĩa 2 сделаться)", viet: "Cái cặp này phục vụ tôi nhiều năm rồi mà vẫn như mới! Nó chẳng hề hấn gì cả!", why: "Ничего не делается (вô nhân xưng) = không có gì xảy ra (với vật), không hư hỏng gì. Cấu trúc: с чем-либо ничего не делается." },
  { id: 5, sentence: "Зачем ты подделал подпись директора?", ans: "подделал — làm giả (chữ ký)", viet: "Tại sao cậu lại giả mạo chữ ký của giám đốc?", why: "СВ подделать = làm giả (tài liệu, chữ ký). Hành vi phạm pháp. Nghĩa rõ ràng, không có nghĩa thứ hai." },
  { id: 6, sentence: "Была авария, но с нами всё в порядке, мы отделались лишь лёгким испугом.", ans: "отделались — thoát ra/qua được chỉ với (một cú sợ nhẹ), nghĩa 3", viet: "Đã có tai nạn, nhưng chúng tôi đều ổn, chúng tôi chỉ bị một phen hú vía (chỉ bị sợ nhẹ).", why: "Отделаться лёгким испугом = thoát hiểm mà chỉ bị sợ chút thôi. Thành ngữ cố định, nghĩa 3." },
  { id: 7, sentence: "Я отделался лишь одной царапиной!", ans: "отделался — thoát nạn chỉ với một vết xước nhỏ (nghĩa 3)", viet: "Tôi chỉ bị một vết xước nhẹ thôi!", why: "Tiếp tục nghĩa 3 отделаться = trải qua mà chỉ bị thiệt hại nhỏ." },
  { id: 8, sentence: "Посмотри, как быстро он разделался с обедом!", ans: "разделался — giải quyết xong, thanh toán gọn (bữa ăn trưa), nghĩa 1 разг.", viet: "Xem kìa, anh ấy giải quyết bữa trưa nhanh chưa!", why: "Разделаться с чем-либо (разг.) = xong xôi, giải quyết nhanh gọn. Thường dùng cho ăn uống, công việc." },
  { id: 9, sentence: "Ну, я с тобой сейчас за это разделаюсь!", ans: "разделаюсь — sẽ tính sổ với mày! (nghĩa *2: наказать)", viet: "Nào, ta sẽ tính sổ với ngươi vì chuyện này bây giờ!", why: "Nghĩa 2 (разделаться с обидчиком) = trừng phạt, \"tính sổ\". Thường mang tính đe dọa/bạo lực." },
  { id: 10, sentence: "Что за глупые шутки?! Что там у вас делается?", ans: "делается — đang xảy ra chuyện gì vậy? (nghĩa 2 сделаться: происходить)", viet: "Những trò đùa ngớ ngẩn gì thế này?! Chuyện gì đang xảy ra với các bạn vậy?", why: "Что делается? = chuyện gì xảy ra vậy? Câu hỏi ngạc nhiên/bực bội. Ngôi 3, вô nhân xưng." },
  { id: 11, sentence: "От выпитого вина ему сделалось плохо.", ans: "сделалось плохо — trở nên thấy khó chịu, buồn nôn (nghĩa 1 сделаться: становиться)", viet: "Do uống rượu nên anh ấy cảm thấy khó chịu.", why: "Сделаться + краткое прилагательное (плохо, хорошо, грустно…) = trở nên (cảm giác). Cấu trúc vô nhân xưng: ему сделалось плохо." },
  { id: 12, sentence: "Вы знаете, как он отделал свою новую квартиру? Это просто сказка!", ans: "отделал — trang trí/hoàn thiện nội thất (căn hộ), nghĩa 1", viet: "Bạn có biết anh ấy đã trang trí căn hộ mới của mình như thế nào không? Thật là một câu chuyện cổ tích!", why: "СВ отделать квартиру = hoàn thiện, trang trí nội thất. Nghĩa tích cực. Khác với nghĩa 3 (mắng/đánh)." },
];

export const d56 = [
  { id: 1, sentence: "Она шьёт ночную рубашку и хочет отделать её кружевами.", ans: "отделать кружевами — trang trí/đính ren (nghĩa 2: украсить)", viet: "Cô ấy đang may áo ngủ và muốn đính ren trang trí cho nó.", why: "" },
  { id: 2, sentence: "Мясник разделывает туши.", ans: "разделывает — mổ xẻ, chế biến thịt (nghĩa 1: привести в состояние)", viet: "Người thợ xẻ thịt đang pha thịt.", why: "Разделывать тушу = mổ/pha thịt. Thuật ngữ chuyên ngành hàng thịt/bếp núc." },
  { id: 3, sentence: "Он умеет прыгать на батуте. Посмотри, какие фигуры он проделывает в воздухе!", ans: "проделывает — thực hiện (các động tác, tiết mục) (nghĩa 2: сделать, выполнить)", viet: "Anh ấy biết nhảy bạt nhún. Nhìn xem anh ấy thực hiện những động tác gì trên không trung kìa!", why: "Проделывать фигуры/трюки = thực hiện các kỹ thuật. НСВ vì hành động lặp lại nhiều lần." },
  { id: 4, sentence: "Крестьянин возделывает свою землю и мечтает получить хороший урожай.", ans: "возделывает — canh tác, cày xới (ruộng đất) — НСВ chủ đạo", viet: "Người nông dân canh tác mảnh đất của mình và mơ ước có một vụ mùa bội thu.", why: "НСВ возделывать (чаще НСВ) = canh tác liên tục. Từ trang trọng/văn viết hơn обрабатывать землю." },
  { id: 5, sentence: "Шкуры животных нужно долго выделывать.", ans: "выделывать — chế biến, thuộc (da) (nghĩa 1: обработать, изготовить)", viet: "Da động vật cần phải được thuộc trong thời gian dài.", why: "НСВ выделывать шкуры = thuộc da, xử lý da thú. Thuật ngữ nghề thủ công." },
  { id: 6, sentence: "Как он мне надоел! Как от него отделаться?", ans: "отделаться — thoát khỏi/loại bỏ (người phiền phức) (nghĩa 1 разг.: избавиться)", viet: "Anh ta làm tôi phát ngán quá! Làm sao để tống khứ anh ta đi đây?", why: "" },
  { id: 7, sentence: "В кольцо вделан великолепный драгоценный камень.", ans: "вделан — được gắn/chế tác vào (nhẫn) (дạng ngắn của страдательного причастия)", viet: "Một viên đá quý tuyệt đẹp được gắn vào chiếc nhẫn.", why: "СВ вделать камень в кольцо = gắn đá quý vào nhẫn. Dạng bị động краткое причастие: камень вделан." },
  { id: 8, sentence: "На него напали хулиганы, но он парень крепкий, и он их так отделал, что они еле ноги унесли!", ans: "отделал — đánh cho nhừ tử (nghĩa *3 прост.: выругать или избить)", viet: "Anh ấy bị đám côn đồ tấn công, nhưng anh ấy là một chàng trai khỏe mạnh và đã đánh chúng cho nhừ tử khiến chúng phải vắt chân lên cổ mà chạy!", why: "Nghĩa 3 (СВ, прост.) của отделать = đánh đập/mắng chửi. Cực kỳ thông tục." },
  { id: 9, sentence: "Кто сказал, что наша команда проиграет вашей? Да мы вас так разделаем, что плохо будет!", ans: "разделаем — sẽ \"xử gọn\" các anh, đánh thắng áp đảo (nghĩa *2 прост.: избить)", viet: "Ai nói đội chúng tôi sẽ thua đội các anh? Chúng tôi sẽ xử đẹp các anh cho mà xem!", why: "Thể thao/khẩu khí đe dọa. Разделать команду (прост.) = đánh bại hoàn toàn." },
  { id: 10, sentence: "Он заделался завсегдатаем этого клуба.", ans: "заделался — trở thành (khách quen) (прост.: стать кем-либо)", viet: "Anh ta đã trở thành khách quen của câu lạc bộ này.", why: "СВ заделаться (прост.) = trở thành ai đó (thường với hàm ý ngạc nhiên hoặc mỉa mai)." },
  { id: 11, sentence: "Не знаю, чем он занят. Наверно, обделывает там какие-то делишки.", ans: "обделывает — đang lo liệu/thu vén (những việc mờ ám) (nghĩa 2 прост.)", viet: "Tôi không biết anh ta đang bận việc gì. Chắc là đang lo liệu mấy việc mờ ám gì đó.", why: "Обделывать делишки (прост.) = mưu mô, thu vén lợi ích cá nhân. Hàm ý tiêu cực." },
  { id: 12, sentence: "Только не надо подделываться под интеллигента!", ans: "подделываться под — giả vờ/bắt chước (dáng vẻ trí thức)", viet: "Chỉ là đừng có giả bộ làm người trí thức!", why: "Подделываться под кого-либо = bắt chước, giả giọng/hành vi của ai. Có sắc thái chê bai." },
];

export const d57 = [
  { id: 1, sentence: "Реферат не закончен, его надо … .", options: ["выделать","доделать"], correct: "доделать", viet: "Bài tiểu luận chưa xong, cần phải làm nốt nó.", why: "Доделать реферат = hoàn thành nốt bài luận. Выделать = thuộc da/chế tác — không liên quan." },
  { id: 2, sentence: "Она … его несчастным.", options: ["наделала","сделала"], correct: "сделала", viet: "Cô ấy đã làm anh ấy bất hạnh.", why: "Сделать кого-либо несчастным = làm ai bất hạnh. Наделала его несчастным — sai cấu trúc, наделать cần tân ngữ ở Р.п." },
  { id: 3, sentence: "У нас будут гости, и мы … всяких разных салатов.", options: ["наделали","проделали"], correct: "наделали", viet: "Chúng tôi sẽ có khách, và chúng tôi đã làm rất nhiều loại salad khác nhau.", why: "Наделать салатов = làm ra nhiều loại salad (Р.п. = số lượng nhiều). Проделали không dùng cho thức ăn." },
  { id: 4, sentence: "Пожалуйста, … мне одолжение: реши за меня эти две задачи!", options: ["проделай","сделай"], correct: "сделай", viet: "Làm ơn giúp tôi một việc: giải hộ tôi hai bài tập này với!", why: "Сделай мне одолжение = làm ơn cho tôi. Thành ngữ cố định. Проделай không dùng trong thành ngữ này." },
  { id: 5, sentence: "Новая квартира готова, теперь надо её … .", options: ["заделать","отделать"], correct: "отделать", viet: "Căn hộ mới đã sẵn sàng, bây giờ cần phải trang trí (hoàn thiện nội thất) nó.", why: "Отделать квартиру = hoàn thiện nội thất (nghĩa 1). Заделать = trám bít khe hở — không phù hợp ngữ cảnh \"квартира готова\"." },
  { id: 6, sentence: "Мы мастерим куклу: вот туловище, сейчас … ручки и ножки — и кукла готова.", options: ["приделаем","разделаем"], correct: "приделаем", viet: "Chúng tôi đang làm búp bê: đây là thân mình, bây giờ sẽ gắn tay và chân vào — và búp bê sẽ xong.", why: "Приделать ручки/ножки = gắn tay/chân vào. Разделаем nghĩa là chia thịt — hoàn toàn không phù hợp." },
  { id: 7, sentence: "Зачем здесь … отверстие?", options: ["приделали","проделали"], correct: "проделали", viet: "Tại sao lại đục cái lỗ ở đây?", why: "Проделать отверстие = đục/khoét lỗ (nghĩa 1). Приделать = gắn thêm vật gì — không tạo ra lỗ." },
  { id: 8, sentence: "Отверстие надо срочно … .", options: ["выделать","заделать"], correct: "заделать", viet: "Cần phải bịt kín cái lỗ này ngay lập tức.", why: "Заделать отверстие = bịt kín lỗ hổng. Cặp đối lập quan trọng: проделать (tạo lỗ) ↔ заделать (bịt lỗ)." },
];

export const d58 = [
  { id: 1, sentence: "Мне … дурно, как только подумаю об экзаменах.", options: ["делает","делается"], correct: "делается", viet: "Tôi thấy khó chịu ngay khi vừa nghĩ đến các kỳ thi.", why: "Мне делается дурно = tôi thấy buồn nôn/chóng mặt. Cấu trúc vô nhân xưng: кому-либо делается + краткое прилагательное/наречие. Делает không dùng theo cách này." },
  { id: 2, sentence: "Зачем бандиты … паспорта?", options: ["подделывают","проделывают"], correct: "подделывают", viet: "Tại sao bọn tội phạm lại làm giả hộ chiếu?", why: "Подделывать паспорта = làm giả hộ chiếu. Проделывать không có nghĩa làm giả tài liệu." },
  { id: 3, sentence: "Это целина, её никто ещё не … .", options: ["возделывал","разделывал"], correct: "возделывал", viet: "Đây là đất hoang, chưa có ai canh tác nó cả.", why: "Возделывать целину = khai hoang, vỡ đất hoang. Разделывать = mổ thịt — không dùng cho đất đai." },
  { id: 4, sentence: "Не стоит … из мухи слона!", options: ["возделывал","делать"], correct: "делать", viet: "Không đáng để chuyện bé xé ra to!", why: "Делать из мухи слона = thành ngữ: thổi phồng, làm chuyện bé xé ra to. Câu hoàn toàn cố định." },
  { id: 5, sentence: "Наконец-то мы … все домашние дела!", options: ["переделали","разделались"], correct: "переделали", viet: "Cuối cùng thì chúng tôi cũng đã làm xong mọi việc nhà!", why: "Переделать все дела = làm xong tất cả việc nhà (nghĩa 2: many). Разделались с делами cũng đúng (разг.) nhưng đòi hỏi предлог С." },
  { id: 6, sentence: "Ты обещал помочь мне. Нет, не завтра, а сегодня! Ты от меня так просто не … !", options: ["отделаешься","разделаешься"], correct: "отделаешься", viet: "Cậu đã hứa giúp tôi mà. Không, không phải mai mà là hôm nay! Cậu không thoát khỏi tôi dễ dàng thế đâu!", why: "Не отделаешься (разг.) = không thoát được/không trốn tránh được (nghĩa 1). Разделаешься nghĩa khác: tính sổ." },
  { id: 7, sentence: "У тебя новое кожаное пальто? Кожа хорошо … .", options: ["выделана","сделана"], correct: "выделана", viet: "Bạn có chiếc áo khoác da mới à? Da được thuộc tốt đấy.", why: "Кожа выделана = da được thuộc/chế biến tốt. Dạng краткое причастие. Сделана quá chung chung, không phù hợp ngữ cảnh da thuộc." },
  { id: 8, sentence: "Ну, вот мы и … с экзаменами! Каникулы!", options: ["переделали","разделались"], correct: "разделались", viet: "Nào, vậy là chúng ta đã giải quyết xong các kỳ thi rồi! Kỳ nghỉ thôi!", why: "Разделались с экзаменами (разг.) = xong hết thi cử rồi! Nghĩa 1. Переделали экзамены sai cấu trúc — переделать không dùng với экзамены theo nghĩa này." },
];

export const d59 = [
  { id: 1, orig: "Разве так можно?! Что ты делаешь!", repl: "наделал", viet: "Lẽ nào có thể như vậy?! Cậu đang làm gì thế! (Thay bằng 'наделал': Cậu đã gây ra chuyện gì thế này!)", ans: "Наделал: thay được, nhưng đổi sang СВ và quá khứ — nghĩa thay đổi: \"Mày đã gây ra bao nhiêu chuyện!\" Câu gốc hỏi về hiện tại." },
  { id: 2, orig: "Мы проделали большую работу.", repl: "сделали", viet: "Chúng tôi đã thực hiện một công việc lớn.", ans: "Сделали: thay được, nghĩa tương tự. Проделали trang trọng hơn, nhấn mạnh hơn vào quá trình." },
  { id: 3, orig: "Статья плохая, её надо переделать.", repl: "доделать", viet: "Bài báo tệ quá, cần phải làm lại.", ans: "Доделать: nghĩa khác — hoàn thành nốt (bài chưa xong). Переделать = làm lại từ đầu. Thay đổi nghĩa đáng kể." },
  { id: 4, orig: "Конечно, он совершил ошибку, но уже ничего не поделаешь!", repl: "сделаешь", viet: "Tất nhiên, anh ấy đã phạm sai lầm, nhưng chẳng làm gì được nữa rồi!", ans: "Ничего не сделаешь: thay được, nghĩa tương tự. Cả hai đều là thành ngữ \"đành chịu\". Поделаешь разг. hơn một chút." },
  { id: 5, orig: "Ребята проделали дыру в заборе.", repl: "заделали", viet: "Các bạn nhỏ đã đục một cái lỗ trên hàng rào.", ans: "Заделали дыру: NGƯỢC nghĩa hoàn toàn! Проделать = tạo lỗ; заделать = bịt lỗ. Không thay được." },
  { id: 6, orig: "Зачем вы подделали подпись начальника?", repl: "переделали, приделали", viet: "Tại sao các bạn lại giả mạo chữ ký của sếp?", ans: "Cả hai đều sai. Переделали подпись = làm lại chữ ký (khác nghĩa). Приделали = gắn thêm vào. Không thay được." },
  { id: 7, orig: "Он здорово проделывает этот фокус!", repl: "делает, разделывает", viet: "Anh ấy thực hiện trò ảo thuật này rất cừ!", ans: "Делает: thay được, nhưng проделывает nhấn mạnh hơn vào kỹ năng. Разделывает = mổ thịt — không phù hợp." },
  { id: 8, orig: "Ваше платье уже сшили, только надо чем-то его украсить, чем-то отделать.", repl: "доделать, приделать", viet: "Váy của bạn đã may xong rồi, chỉ cần trang trí thêm gì đó vào thôi.", ans: "Доделать: thay được (hoàn thiện thêm). Приделать: cần tân ngữ cụ thể (приделать украшение), không dùng một mình được." },
];

export const d60 = [
  { id: 1, prompt: "Кто что делает сегодня вечером — …?", ans: "— Кто что делает сегодня вечером?— Я буду готовиться к экзамену, а мой друг пойдёт в кино.", viet: "— Ai làm gì tối nay thế? — Tôi sẽ ôn thi, còn bạn tôi đi xem phim.", why: "" },
  { id: 2, prompt: "Какие дела необходимо переделать завтра — …?", ans: "— Какие дела необходимо переделать завтра?— Надо переделать доклад: преподаватель сказал, что структура неправильная.", viet: "— Những việc gì cần phải làm lại vào ngày mai? — Cần phải làm lại bản báo cáo: giảng viên nói rằng cấu trúc bị sai.", why: "" },
  { id: 3, prompt: "Кто наделал ошибок в контрольной работе — …?", ans: "— Кто наделал ошибок в контрольной работе?— К сожалению, почти все студенты наделали много ошибок.", viet: "— Ai đã phạm lỗi trong bài kiểm tra? — Thật không may, hầu hết sinh viên đều phạm nhiều lỗi.", why: "Наделать ошибок (Р.п.) = phạm nhiều lỗi. Cụm cố định hay gặp." },
  { id: 4, prompt: "Где и какие щели và дыры надо заделать — …?", ans: "— Где и какие щели нужно заделать?— В ванной есть трещина в стене, её нужно срочно заделать цементом.", viet: "— Ở đâu và những khe hở, lỗ hổng nào cần bịt kín? — Trong phòng tắm có một vết nứt trên tường, cần phải bịt kín nó bằng xi măng ngay.", why: "" },
  { id: 5, prompt: "Кто проделал огромную работу — …?", ans: "— Кто проделал огромную работу по подготовке конференции?— Весь наш отдел работал над этим три месяца.", viet: "— Ai đã thực hiện một khối lượng công việc khổng lồ để chuẩn bị cho hội nghị? — Toàn bộ phòng ban của chúng tôi đã làm việc này trong ba tháng.", why: "" },
  { id: 6, prompt: "От кого вы никак không thể отделаться — …?", ans: "— От кого вы никак не можете отделаться?— Никак не могу отделаться от одного навязчивого знакомого — звонит каждый день!", viet: "— Bạn không thể tống khứ ai đi được? — Tôi không thể tống khứ được một người quen lèo nhèo — cứ gọi điện mỗi ngày!", why: "Отделаться от кого-либо (разг.) = thoát khỏi ai phiền phức. Cấu trúc: отделаться от + Р.п." },
  { id: 7, prompt: "С кем или с чем có thể nhanh chóng разделаться — …?", ans: "— С чем можно быстро разделаться?— Думаю, с этим несложным заданием можно разделаться за полчаса.", viet: "— Có thể nhanh chóng giải quyết xong việc gì? — Tôi nghĩ là có thể giải quyết xong bài tập không khó này trong nửa tiếng.", why: "Разделаться с чем-либо (разг.) = giải quyết xong nhanh gọn. Cấu trúc: разделаться с + Т.п." },
  { id: 8, prompt: "Кто и зачем подделывает документы — …?", ans: "— Кто и зачем подделывает документы?— К сожалению, некоторые люди подделывают документы ради личной выгоды.", viet: "— Ai và tại sao lại làm giả giấy tờ? — Thật không may, một số người làm giả giấy tờ vì lợi ích cá nhân.", why: "" },
  { id: 9, prompt: "Sinh viên thực hiện những mánh khóe gì trong kỳ thi — …?", ans: "— Какие фокусы студенты проделывают на экзаменах?— Некоторые проделывают невероятные фокусы: пишут шпаргалки на руках и прячут телефоны.", viet: "— Sinh viên thực hiện những mánh khóe gì trong kỳ thi? — Một số người thực hiện những mánh khóe khó tin: viết phao lên tay và giấu điện thoại.", why: "Проделывать фокусы/трюки = thực hiện mánh khoé, thủ thuật. Nghĩa 2." },
  { id: 10, prompt: "Chuyện gì đang xảy ra ở ký túc xá những ngày này vậy — …?", ans: "— Что делается в общежитии в эти дни?— Там такой шум и беспорядок! Студенты готовятся к сессии, кто-то кричит, кто-то смеётся.", viet: "— Chuyện gì đang xảy ra ở ký túc xá những ngày này vậy? — Ở đó thật ồn ào và lộn xộn! Sinh viên đang ôn thi, người thì hét, người thì cười.", why: "Что делается? = Chuyện gì đang xảy ra? Cấu trúc vô nhân xưng, nghĩa 2 сделаться: происходить." },
];
