export const r47 = [
  { id: 1, sentence: "Кем работает твой отец?", ans: "работает — nghĩa 3: иметь должность (làm nghề gì, giữ chức vụ gì)", viet: "Bố bạn làm nghề gì?", why: "Câu hỏi về nghề nghiệp. Dùng НСВ vì đây là trạng thái thường xuyên/ổn định." },
  { id: 2, sentence: "Я хочу сначала поработать, а уже потом поступать в аспирантуру.", ans: "поработать — làm việc một thời gian (nghĩa ngắn), có giới hạn thời gian", viet: "Tôi muốn làm việc một thời gian trước, sau đó mới thi cao học.", why: "СВ поработать = làm việc trong thời gian nhất định, không kéo dài mãi. Tương phản với работать НСВ." },
  { id: 3, sentence: "Телевизор не работает, надо ремонтировать.", ans: "работает — nghĩa 1: находиться в действии (hoạt động, vận hành)", viet: "Tivi không hoạt động, cần phải sửa thôi.", why: "Chủ thể là vật/thiết bị. НСВ vì đây là trạng thái hiện tại." },
  { id: 4, sentence: "Отец проработал на этом заводе десять лет.", ans: "проработал — làm việc suốt (10 năm liên tục)", viet: "Bố tôi đã làm việc tại nhà máy này suốt 10 năm.", why: "СВ проработать = làm việc trong một khoảng thời gian dài xác định (có đích). Khác với работал НСВ (không nhấn mạnh khoảng thời gian)." },
  { id: 5, sentence: "Он уже доработал до пенсии.", ans: "доработал — làm việc đến tận (ngày về hưu), đạt tới một mốc thời gian", viet: "Ông ấy đã làm việc cho đến tận khi nghỉ hưu.", why: "Доработать до + Р.п. = làm việc đến/tới mốc nào đó. СВ nhấn mạnh việc đạt đến đích (до пенсии)." },
  { id: 6, sentence: "Можно спросить: сколько ты зарабатываешь?", ans: "зарабатываешь — kiếm (bao nhiêu tiền), nghĩa 1 НСВ", viet: "Có thể hỏi bạn kiếm được bao nhiêu tiền không?", why: "НСВ = hành động lặp lại/thường xuyên (thu nhập đều đặn hàng tháng)." },
  { id: 7, sentence: "Этот писатель сейчас работает над новым романом.", ans: "работает над — đang làm việc trên/với (tác phẩm mới)", viet: "Nhà văn này hiện đang viết một cuốn tiểu thuyết mới.", why: "Работать над + Т.п. = làm việc, nghiên cứu về cái gì đó. Cấu trúc quan trọng cần nhớ." },
  { id: 8, sentence: "Машина долго не заводилась, но наконец мотор заработал.", ans: "заработал — bắt đầu hoạt động/vận hành (nghĩa 3 của заработать)", viet: "Xe mãi không nổ máy, nhưng cuối cùng thì động cơ cũng đã hoạt động.", why: "СВ заработать = bắt đầu hoạt động (về máy móc, thiết bị). Chú ý đây là nghĩa 3, không phải nghĩa \"kiếm tiền\"." },
  { id: 9, sentence: "Мы прекрасно отработали на практике.", ans: "отработали — hoàn thành/kết thúc tốt đợt thực tập (nghĩa 3: кончить работать)", viet: "Chúng tôi đã hoàn thành kỳ thực tập rất tốt.", why: "СВ отработать = hoàn thành ca làm/kỳ thực tập. Có sắc thái \"đã làm xong, hoàn thành\"." },
  { id: 10, sentence: "Мой друг учится в университете и подрабатывает в газете.", ans: "подрабатывает — làm thêm (ngoài giờ học), kiếm thêm chút ít", viet: "Bạn tôi đang học đại học và làm thêm ở một tòa soạn báo.", why: "НСВ подрабатывать = làm thêm, part-time. Khẩu ngữ, thường gặp ở sinh viên." },
];

export const r48 = [
  { id: 1, sentence: "Это важные научные статьи, вам следует их серьёзно проработать.", ans: "проработать — nghiên cứu kỹ, đào sâu (nghĩa 2 разг.)", viet: "Đây là những bài báo khoa học quan trọng, bạn nên nghiên cứu chúng một cách nghiêm túc.", why: "СВ проработать nghĩa 2 = đọc/nghiên cứu thấu đáo từng chi tiết. Ít trang trọng hơn изучить." },
  { id: 2, sentence: "Этот учёный выдвинул и разработал принципиально новую систему исследования.", ans: "разработал — xây dựng/phát triển (hệ thống mới), nghĩa 2: исследовать, подготовить", viet: "Nhà khoa học này đã đề xuất và xây dựng một hệ thống nghiên cứu hoàn toàn mới.", why: "СВ разработать = phát triển, nghiên cứu xây dựng. Thuật ngữ khoa học/kỹ thuật, văn phong trang trọng." },
  { id: 3, sentence: "Следует выработать план действий.", ans: "выработать — xây dựng (kế hoạch), nghĩa 2 перен.: обдумывая, создать", viet: "Cần phải xây dựng một kế hoạch hành động.", why: "Выработать план là cụm từ cố định. Khác với разработать план (разработать nhấn mạnh quá trình nghiên cứu chi tiết hơn)." },
  { id: 4, sentence: "План не совсем удачный, его надо переработать.", ans: "переработать — làm lại, sửa lại (nghĩa 2)", viet: "Kế hoạch này chưa ổn lắm, cần phải soạn lại/sửa lại.", why: "СВ переработать = viết/soạn lại. Nghĩa 2, khác với nghĩa 1 (chế biến nguyên liệu) và nghĩa 3 (làm quá giờ)." },
  { id: 5, sentence: "Что вырабатывают из нефти?", ans: "вырабатывают — sản xuất, chế biến ra (từ dầu mỏ), nghĩa 1", viet: "Người ta sản xuất ra gì từ dầu mỏ?", why: "НСВ = hành động thường xuyên/tổng quát. Nghĩa 1 = sản xuất vật chất." },
  { id: 6, sentence: "У меня уже выработалась привычка рано вставать.", ans: "выработалась — hình thành (thói quen) theo thời gian", viet: "Tôi đã hình thành thói quen dậy sớm.", why: "СВ выработатьcя = xuất hiện/hình thành nhờ kinh nghiệm, thực hành lặp đi lặp lại. Ngôi 1&2 không dùng được." },
  { id: 7, sentence: "В желудке пища перерабатывается.", ans: "перерабатывается — được chuyển hóa (thức ăn trong dạ dày), nghĩa 1 перерабатываться", viet: "Thức ăn được chuyển hóa trong dạ dày.", why: "Ngôi 3 (vật vô nhân xưng). Dùng НСВ vì đây là quá trình sinh học diễn ra liên tục." },
  { id: 8, sentence: "Он уже ушёл домой? Да, он не переработает!", ans: "не переработает — (mỉa mai) anh ấy không bao giờ làm quá giờ đâu (nghĩa 3: làm quá giờ)", viet: "Anh ta về nhà rồi à? Phải, anh ta không bao giờ làm quá giờ đâu!", why: "Mang sắc thái mỉa mai/hài hước. Переработать nghĩa 3 (разг.) = làm việc quá giờ quy định." },
  { id: 9, sentence: "Ух, мы сегодня за день наработались!", ans: "наработались — làm đã đủ, mệt bở hơi tai (разг.)", viet: "Ôi, hôm nay chúng tôi đã làm việc mệt bở hơi tai cả ngày rồi!", why: "СВ наработаться = đã làm đủ/thỏa thích đến mức kiệt sức. Khẩu ngữ, biểu cảm mạnh." },
  { id: 10, sentence: "Отдохни, а то ты совсем заработался!", ans: "заработался — bị cuốn vào làm việc quá mức, kiệt sức", viet: "Nghỉ ngơi đi, bạn mải làm việc quá mức rồi đấy!", why: "СВ заработаться = mải làm đến mức quên mọi thứ, kiệt sức. Thường dùng với sắc thái lo lắng/quan tâm." },
  { id: 11, sentence: "Надо обработать рану спиртом.", ans: "обработать — xử lý, sát trùng (vết thương), nghĩa 1", viet: "Cần phải sát trùng vết thương bằng cồn.", why: "СВ обработать nghĩa 1 = xử lý y tế. Cụm обработать рану là cụm từ cố định trong lĩnh vực y tế." },
  { id: 12, sentence: "Вы пропустили занятие, вам нужно его отработать.", ans: "отработать — bù lại (buổi học đã bỏ), nghĩa 1: возместить", viet: "Bạn đã bỏ lỡ buổi học, bạn cần phải học bù.", why: "СВ отработать nghĩa 1 = bù đắp bằng công sức. Отработать занятие = học bù." },
];

export const r49 = [
  { id: 1, sentence: "Что-то мне не работается сегодня!", ans: "работается — (vô nhân xưng разг.) cảm giác không muốn/không thể làm việc hôm nay", viet: "Hôm nay tôi cứ thấy không muốn làm việc thế nào ấy!", why: "Работаться — cấu trúc vô nhân xưng. Chủ thể ở 3 cách: мне не работается. Diễn đạt trạng thái chủ quan về việc làm việc." },
  { id: 2, sentence: "Пересядь подальше от окна, а то заработаешь бронхит!", ans: "заработаешь — (мỉa mai) sẽ \"kiếm được\" bệnh viêm phế quản (nghĩa *2 разг. ирон.)", viet: "Ngồi xa cửa sổ ra, không là bị viêm phế quản đấy!", why: "Nghĩa 2 của заработать (разг., ирон.) = nhận/hứng chịu hậu quả xấu. Đây là cách dùng hài hước, mỉa mai." },
  { id: 3, sentence: "Твою статью надо лишь немного подработать — и можно печатать.", ans: "подработать — hoàn thiện thêm một chút (nghĩa 2: немного доделать)", viet: "Bài viết của bạn chỉ cần chỉnh sửa thêm một chút là có thể đem in được rồi.", why: "Подработать nghĩa 2 = chỉnh sửa nhỏ, hoàn thiện thêm. Nghĩa này ít gặp hơn nghĩa 1 (kiếm thêm tiền)." },
  { id: 4, sentence: "Отлично сработано!", ans: "сработано — được làm ra xuất sắc (прост., nghĩa 1: сделать, изготовить)", viet: "Làm tốt lắm! / Chế tạo tuyệt quá!", why: "Dạng краткое причастие của сработать (прост.) = chế tạo/làm ra. Cụm отлично сработано! = Làm tuyệt lắm! (thông tục)." },
  { id: 5, sentence: "Вы прекрасный специалист. Думаю, мы с вами сработаемся.", ans: "сработаемся — sẽ ăn ý với nhau, hợp tác tốt được", viet: "Bạn là một chuyên gia giỏi. Tôi nghĩ chúng ta sẽ hợp tác ăn ý với nhau.", why: "СВ сработаться = đạt được sự phối hợp nhịp nhàng trong công việc. Chủ thể phải ở ngôi nhiều người." },
  { id: 6, sentence: "Крестьянин разрабатывает свой участок.", ans: "разрабатывает — khai phá/vỡ hoang mảnh đất (nghĩa 1: сделать пригодным)", viet: "Người nông dân đang khai phá mảnh đất của mình.", why: "НСВ разрабатывать nghĩa 1 = làm cho đất đai phù hợp để canh tác. Hành động diễn ra liên tục." },
  { id: 7, sentence: "Помоги мне сделать грядку. На! Поработай лопатой!", ans: "поработай лопатой — làm việc một lúc bằng xẻng (nghĩa 5 работать: управлять лопатой)", viet: "Giúp tôi làm cái luống với. Này! Cầm xẻng làm một lát đi!", why: "Работать/поработать + Т.п. (lопатой, руками…) = sử dụng công cụ để làm. Nghĩa 5." },
  { id: 8, sentence: "Он часто опаздывает, вот его сегодня и прорабатывали на собрании.", ans: "прорабатывали — phê bình tập thể tại cuộc họp (nghĩa *3 разг., шутл.)", viet: "Anh ta hay đi muộn, nên hôm nay bị đem ra phê bình trong cuộc họp.", why: "Nghĩa 3 (разг., шутл.) của прорабатывать = chỉ trích, phê bình ai đó trước tập thể. Hài hước/mỉa mai." },
  { id: 9, sentence: "Заработок маленький, и надо где-то ещё прирабатывать.", ans: "прирабатывать — kiếm thêm ngoài thu nhập chính", viet: "Thu nhập ít ỏi, nên cần phải kiếm thêm ở đâu đó nữa.", why: "Прирабатывать = kiếm thêm ngoài lương chính. Gần nghĩa với подрабатывать nhưng nhấn mạnh phần thu nhập phụ thêm (при-)." },
  { id: 10, sentence: "Ну что, много наработал сегодня?", ans: "наработал — (разг.) làm ra được nhiều không? (hàm ý mỉa mai)", viet: "Sao, hôm nay làm được nhiều không? (mỉa mai)", why: "СВ наработать (разг.) = làm ra nhiều. Thường dùng với hàm ý mỉa mai khi hỏi người lười." },
  { id: 11, sentence: "Всё! Отдыхаем! Совсем уработались!", ans: "уработались — kiệt sức vì làm nhiều quá (прост.)", viet: "Xong rồi! Nghỉ thôi! Mệt lả người vì làm việc rồi!", why: "СВ уработаться (прост.) = mệt lả vì làm việc. Thông tục, biểu cảm mạnh. Tương tự наработаться, заработаться." },
  { id: 12, sentence: "Так и до инфаркта можно доработаться!", ans: "доработаться — (разг., tiêu cực) làm đến mức tự hủy hoại bản thân", viet: "Cứ thế này thì có ngày làm việc đến mức nhồi máu cơ tim mất!", why: "СВ доработаться (разг., негативное) = làm việc căng thẳng đến mức gây hại cho sức khỏe. До инфаркта = đến mức nhồi máu cơ tim." },
];

export const r50 = [
  { id: 1, sentence: "Мой дедушка … до пенсии.", options: ["выработал","доработал"], correct: "доработал", viet: "Ông tôi đã làm việc đến tận khi nghỉ hưu.", why: "Доработать до пенсии = làm đến tận ngày về hưu. Выработать nghĩa là sản xuất ra — không phù hợp ngữ cảnh." },
  { id: 2, sentence: "Он уже … положенные для пенсии двадцать лет.", options: ["заработал","отработал"], correct: "отработал", viet: "Ông ấy đã làm việc đủ 20 năm theo quy định để nghỉ hưu.", why: "Отработать + время = làm đủ số năm/giờ quy định. Заработал nghĩa là kiếm được tiền — không phù hợp." },
  { id: 3, sentence: "Он всегда много … .", options: ["зарабатывал","прорабатывал"], correct: "зарабатывал", viet: "Anh ấy luôn kiếm được nhiều tiền.", why: "Зарабатывать много = kiếm được nhiều tiền. Прорабатывал много có thể nói được nhưng ít tự nhiên hơn trong ngữ cảnh thu nhập." },
  { id: 4, sentence: "Ты будешь … пропущенные семинарские занятия?", options: ["зарабатывать","отрабатывать"], correct: "отрабатывать", viet: "Bạn sẽ học bù các buổi hội thảo bị bỏ lỡ chứ?", why: "Отрабатывать занятия = học bù. Chỉ отрабатывать có nghĩa \"bù đắp bằng công sức/thời gian\"." },
  { id: 5, sentence: "Я хочу … эту тему.", options: ["выработать","разработать"], correct: "разработать", viet: "Tôi muốn nghiên cứu/phát triển đề tài này.", why: "Разработать тему = phát triển/nghiên cứu đề tài. Выработать тему không đúng — выработать cần tân ngữ là kế hoạch, chương trình, thói quen..." },
  { id: 6, sentence: "Рабочий … детали на станке.", options: ["обрабатывает","перерабатывает"], correct: "обрабатывает", viet: "Người công nhân đang gia công chi tiết trên máy công cụ.", why: "Обрабатывать детали = gia công chi tiết (trên máy tiện). Перерабатывать = chuyển hóa/biến đổi thành thứ khác — không phù hợp." },
  { id: 7, sentence: "Ему сегодня хорошо … .", options: ["работается","работает"], correct: "работается", viet: "Hôm nay anh ấy thấy làm việc rất hiệu quả/thoải mái.", why: "Работается — cấu trúc vô nhân xưng, diễn đạt trạng thái: ему хорошо работается = anh ấy cảm thấy làm việc tốt hôm nay. Không thể dùng работает theo cách này." },
  { id: 8, sentence: "Он … всю ночь.", options: ["переработал","проработал"], correct: "проработал", viet: "Anh ấy đã làm việc suốt đêm.", why: "Theo đáp án sách: переработал. Nhưng проработал cũng tự nhiên với ngữ cảnh \"thời gian cụ thể\" (всю ночь)." },
  { id: 9, sentence: "Он … до утра.", options: ["заработался","переработался"], correct: "заработался", viet: "Anh ấy đã mải làm việc đến tận sáng.", why: "Заработаться до утра = mải làm đến tận sáng. Переработаться = kiệt sức do làm quá giờ — đúng ngữ nghĩa nhưng заработаться tự nhiên hơn với до утра." },
  { id: 10, sentence: "Надо знать меру: работай, но не … !", options: ["перерабатывай","разрабатывай"], correct: "перерабатывай", viet: "Cần biết chừng mực: làm việc đi, nhưng đừng làm quá sức!", why: "Не перерабатывай = đừng làm quá sức. Разрабатывай = hãy phát triển — hoàn toàn khác nghĩa, không phù hợp." },
];

export const r51 = [
  { id: 1, sentence: "Он закаляет волю, … характер.", options: ["вырабатывает","разрабатывает"], correct: "вырабатывает", viet: "Anh ấy rèn luyện ý chí, xây dựng tính cách.", why: "Вырабатывать характер = rèn giũa, xây dựng tính cách (qua quá trình luyện tập). Đây là cụm cố định. Разрабатывать = phát triển đề án/kế hoạch — không dùng cho tính cách." },
  { id: 2, sentence: "Мы сегодня так устали, так … !", options: ["доработались","наработались"], correct: "наработались", viet: "Hôm nay chúng tôi mệt quá, đã làm việc kiệt sức rồi!", why: "Наработаться = làm đã mệt. Cả hai gần nghĩa nhưng наработаться nhấn mạnh \"đã làm đủ/đến mức kiệt sức\". Доработаться có nghĩa tiêu cực hơn (đến mức hại bản thân)." },
  { id: 3, sentence: "Для написания диссертации необходимо … массу специальной литературы.", options: ["подработать","переработать"], correct: "переработать", viet: "Để viết luận án, cần phải đọc qua một khối lượng lớn tài liệu chuyên môn.", why: "Переработать литературу = đọc qua, tiêu hóa một khối lượng lớn tài liệu. Đây là cách dùng đặc biệt của переработать trong học thuật. Подработать không phù hợp." },
  { id: 4, sentence: "На тренировке спортсмен … труднейший прыжок.", options: ["отрабатывал","обрабатывал"], correct: "отрабатывал", viet: "Trong buổi tập, vận động viên đã rèn luyện thuần thục cú nhảy khó nhất.", why: "Отрабатывать прыжок = luyện tập thuần thục kỹ thuật nhảy (nghĩa 5: получить навык). Обрабатывал không dùng cho kỹ năng thể thao." },
  { id: 5, sentence: "Не опаздывай, а то … выговор от начальника!", options: ["заработаешь","отработаешь"], correct: "заработаешь", viet: "Đừng đi muộn, kẻo bị sếp khiển trách đấy!", why: "Заработать выговор (разг., ирон.) = bị nhận khiển trách (nghĩa 2 ирон.). Cụm cố định hay gặp." },
  { id: 6, sentence: "На этом заводе … макулатуру.", options: ["вырабатывают","перерабатывают"], correct: "перерабатывают", viet: "Tại nhà máy này, người ta tái chế giấy vụn.", why: "Перерабатывать макулатуру = tái chế giấy vụn (chuyển hóa thành thứ khác, nghĩa 1). Вырабатывать cũng dùng được nhưng перерабатывать đúng hơn với nguyên liệu tái chế." },
  { id: 7, sentence: "Ты порезался! Надо чем-то … рану!", options: ["обработать","разработать"], correct: "обработать", viet: "Bạn bị đứt tay rồi! Cần phải sát trùng vết thương đi!", why: "Обработать рану = sát trùng, xử lý vết thương. Cụm cố định y tế. Разработать hoàn toàn khác nghĩa." },
  { id: 8, sentence: "Статья сырая, её надо … .", options: ["переработать","разработать"], correct: "переработать", viet: "Bài báo còn thô, cần phải soạn lại.", why: "Переработать статью = viết lại, sửa lại bài viết (nghĩa 2). Статья сырая = bài còn thô, chưa hoàn chỉnh." },
  { id: 9, sentence: "Лучше не занимать деньги: придётся … долги!", options: ["зарабатывать","отрабатывать"], correct: "отрабатывать", viet: "Tốt nhất là đừng vay tiền: sẽ phải đi làm để trả nợ đấy!", why: "Отрабатывать долги = trả nợ bằng sức lao động. Зарабатывать = kiếm tiền (tổng quát hơn)." },
  { id: 10, sentence: "Уже пора домой: мы и так … несколько часов!", options: ["заработались","переработали"], correct: "переработали", viet: "Đến lúc về nhà rồi: chúng ta đã làm thêm mấy tiếng đồng hồ rồi!", why: "Переработали несколько часов = đã làm thêm mấy tiếng. Заработались cũng được nhưng переработать với thời gian cụ thể tự nhiên hơn." },
];

export const r52 = [
  { id: 1, orig: "Он работал всю ночь.", repl: "проработал / заработался", viet: "Anh ấy đã làm việc suốt đêm.", ans: "Проработал: đúng, nhấn mạnh thời gian liên tục (СВ). Заработался: đúng, thêm nghĩa \"mải làm quên thời gian\" (разг.)." },
  { id: 2, orig: "На этом заводе он отработал три года.", repl: "проработал", viet: "Tại nhà máy này, ông ấy đã làm việc đủ 3 năm.", ans: "Проработал thay được, nghĩa tương tự. Отработал nhấn mạnh nghĩa vụ đã hoàn thành; проработал chỉ đơn thuần nói thời gian." },
  { id: 3, orig: "Надо разработать план.", repl: "выработать / переработать", viet: "Cần phải xây dựng một kế hoạch.", ans: "Выработать план: đúng, gần nghĩa. Переработать план: chỉ đúng nếu kế hoạch đã có và cần làm lại — ngữ nghĩa khác." },
  { id: 4, orig: "Следует подработать статью.", repl: "доработать / переработать", viet: "Cần phải hoàn thiện thêm bài báo này.", ans: "Доработать: đúng, hoàn thiện thêm. Переработать: làm lại toàn bộ — mạnh hơn, thay đổi nghĩa." },
  { id: 5, orig: "Ух, мы сегодня переработали!", repl: "заработались / наработались / уработались", viet: "Ôi, hôm nay chúng tôi đã làm việc quá sức/quá giờ rồi!", ans: "Cả ba đều thay được với nghĩa \"kiệt sức\". Khác biệt phong cách: переработали trung tính; наработались разг.; уработались прост." },
];

export const r53 = [
  { id: 1, prompt: "Над какой темой вы работаете — …?", ans: "— Над какой темой вы работаете?— Я работаю над историей русской литературы XIX века.", viet: "Bạn đang làm về đề tài gì? — Tôi đang nghiên cứu về lịch sử văn học Nga thế kỷ 19.", why: "Работать над + Т.п. = nghiên cứu/làm về đề tài nào đó." },
  { id: 2, prompt: "Сколько надо зарабатывать — …?", ans: "— Сколько надо зарабатывать, чтобы жить нормально?— Думаю, не меньше пятидесяти тысяч рублей в месяц.", viet: "Cần kiếm bao nhiêu tiền để sống bình thường? — Tôi nghĩ ít nhất 50 nghìn rúp một tháng.", why: "" },
  { id: 3, prompt: "Какую привычку необходимо выработать — …?", ans: "— Какую привычку необходимо выработать, чтобы хорошо учиться?— Нужно выработать привычку читать каждый день.", viet: "Cần hình thành thói quen gì để học tốt? — Cần hình thành thói quen đọc sách mỗi ngày.", why: "" },
  { id: 4, prompt: "Что вырабатывают из нефти — …?", ans: "— Что вырабатывают из нефти?— Из нефти вырабатывают бензин, пластик и многое другое.", viet: "Người ta sản xuất gì từ dầu mỏ? — Từ dầu mỏ người ta sản xuất xăng, nhựa và nhiều thứ khác.", why: "" },
  { id: 5, prompt: "Сколько лет нужно отработать, чтобы стать хорошим специалистом — …?", ans: "— Сколько лет нужно отработать, чтобы стать хорошим специалистом?— Говорят, что нужно не менее десяти лет практики.", viet: "Cần làm bao nhiêu năm để trở thành chuyên gia giỏi? — Người ta nói cần ít nhất 10 năm thực hành.", why: "" },
  { id: 6, prompt: "Когда растения активно вырабатывают кислород — …?", ans: "— Когда растения активно вырабатывают кислород?— Они вырабатывают кислород в светлое время суток.", viet: "Khi nào cây cối sản sinh oxy? — Chúng sản sinh oxy vào ban ngày khi có ánh sáng.", why: "" },
  { id: 7, prompt: "Кто часто подрабатывает — …?", ans: "— Кто часто подрабатывает в наше время?— Чаще всего студенты и молодые специалисты.", viet: "Ai hay làm thêm hiện nay? — Thường là sinh viên và các chuyên gia trẻ.", why: "" },
  { id: 8, prompt: "Когда вам лучше работается: утром или вечером — …?", ans: "— Когда вам лучше работается: утром или вечером?— Мне лучше работается утром, пока голова свежая.", viet: "Khi nào bạn làm việc tốt hơn: sáng hay tối? — Tôi làm việc tốt hơn vào buổi sáng khi đầu óc còn minh mẫn.", why: "Cấu trúc vô nhân xưng работается + дательный падеж người trải nghiệm." },
  { id: 9, prompt: "Кто советует переработать статью — …?", ans: "— Кто советует переработать статью?— Научный руководитель считает, что нужно полностью переработать введение.", viet: "Ai khuyên nên soạn lại bài báo? — Người hướng dẫn khoa học cho rằng cần soạn lại hoàn toàn phần mở đầu.", why: "" },
  { id: 10, prompt: "Кто может заработаться до утра — …?", ans: "— Кто может заработаться до утра?— Программисты часто заработываются и не замечают, как наступает утро.", viet: "Ai có thể mải làm đến tận sáng? — Các lập trình viên thường mải làm việc mà không nhận ra trời đã sáng.", why: "" },
  { id: 11, prompt: "Кто из родственников доработал до пенсии — …?", ans: "— Кто из родственников доработал до пенсии?— Мой дед доработал до шестидесяти пяти лет и ушёл на заслуженный отдых.", viet: "Ai trong họ hàng của bạn đã làm việc đến tận lúc nghỉ hưu? — Ông tôi đã làm việc đến năm 65 tuổi và đã nghỉ hưu.", why: "" },
  { id: 12, prompt: "Кто должен обработать собранный для статьи материал — …?", ans: "— Кто должен обработать собранный для статьи материал?— Обычно это делает сам автор, но иногда помогает лаборант.", viet: "Ai phải xử lý tài liệu thu thập được cho bài báo? — Thường là tác giả tự làm, nhưng đôi khi có trợ lý giúp đỡ.", why: "" },
];
