export const slushatEx37 = [
  { id: 1, sentence: "Была летняя ночь, мы невольно … пением соловья.", options: ["заслушались", "прислушались"], correct: "заслушались", viet: "Đêm hè ấy, chúng tôi vô tình say mê tiếng chim sơn ca.", why: "заслушаться = mê mẩn vì nghe hay." },
  { id: 2, sentence: "Как красиво поёт: слушаю и не могу … !", options: ["заслушаться", "наслушаться"], correct: "наслушаться", viet: "Cô ấy hát hay quá, nghe mãi không chán!", why: "не могу наслушаться = nghe mãi không chán (nghe không đủ)." },
  { id: 3, sentence: "Ребёнок совсем не … родителей.", options: ["прислушивается", "слушается"], correct: "слушается", viet: "Đứa trẻ hoàn toàn không nghe lời bố mẹ.", why: "слушаться = vâng lời, nghe lời." },
  { id: 4, sentence: "Он обожал эту симфонию, … в каждый её аккорд.", options: ["вслушивался", "заслушивался"], correct: "вслушивался", viet: "Anh ấy yêu bản giao hưởng đó và lắng nghe từng hợp âm.", why: "вслушиваться в ... = chú tâm vào từng âm thanh." },
  { id: 5, sentence: "Плохо, что ты не … к моим советам.", options: ["слушаешься", "прислушиваешься"], correct: "прислушиваешься", viet: "Tệ là cậu không chịu lắng nghe lời khuyên của tôi.", why: "прислушиваться к советам = lưu tâm tới lời khuyên." },
  { id: 6, sentence: "Мы … всех желающих выступить на сегодняшнем заседании.", options: ["заслушаем", "подслушаем"], correct: "заслушаем", viet: "Chúng tôi sẽ nghe tất cả những người muốn phát biểu tại cuộc họp hôm nay.", why: "заслушать dùng trong văn cảnh cuộc họp trang trọng." },
  { id: 7, sentence: "Алло! Я … вас!", options: ["заслушаю", "слушаю"], correct: "слушаю", viet: "A lô, tôi đang nghe đây ạ.", why: "Công thức chuẩn khi nghe điện thoại." },
  { id: 8, sentence: "Он … и услышал чей-то негромкий голос.", options: ["заслушался", "прислушался"], correct: "прислушался", viet: "Anh ấy lắng tai nghe và nghe thấy một giọng nói khẽ.", why: "прислушаться = ghé tai nghe." },
  { id: 9, sentence: "Как тебе не стыдно … !", options: ["заслушивать", "подслушивать"], correct: "подслушивать", viet: "Sao cậu không thấy xấu hổ khi nghe lén!", why: "подслушивать = nghe lén." },
  { id: 10, sentence: "… звучащий текст и ответьте на вопросы теста.", options: ["Выслушайте", "Прослушайте"], correct: "Прослушайте", viet: "Hãy nghe đoạn văn đang phát và trả lời câu hỏi bài kiểm tra.", why: "Trong ngữ cảnh bài thi nghe, dùng прослушайте." },
  { id: 11, sentence: "Извини, я задумался и … , что ты сказал.", options: ["дослушал", "прослушал"], correct: "прослушал", viet: "Xin lỗi, tớ mải suy nghĩ nên đã bỏ sót điều cậu nói.", why: "прослушать = nghe sót, bỏ lỡ." },
  { id: 12, sentence: "Он … родителей и не стал учиться.", options: ["ослушался", "прислушался"], correct: "ослушался", viet: "Anh ta cãi lời bố mẹ và không đi học nữa.", why: "ослушаться = cãi lời, không tuân theo." },
  { id: 13, sentence: "Я хочу, чтобы ты … всё, что я скажу!", options: ["вслушался", "выслушал"], correct: "выслушал", viet: "Tôi muốn anh nghe hết tất cả những gì tôi sẽ nói!", why: "выслушать = nghe hết toàn bộ." },
  { id: 14, sentence: "В университете она … курс лекций по русской истории.", options: ["выслушала", "прослушала"], correct: "прослушала", viet: "Ở đại học cô ấy đã học/nghe trọn khóa bài giảng về lịch sử Nga.", why: "прослушать курс = theo học trọn khóa." }
];

export const slushatAnalysis36 = [
  { id: 1, sentence: "Вслушайтесь в эти волшебные звуки музыки!", ans: "вслушайтесь", viet: "Hãy lắng thật kỹ những âm thanh kỳ diệu này.", why: "вслушаться = tập trung nghe kỹ." },
  { id: 2, sentence: "Выслушайте меня!", ans: "выслушайте", viet: "Hãy nghe tôi nói hết!", why: "выслушать = nghe ai đó nói từ đầu đến cuối." },
  { id: 3, sentence: "Врач старательно прослушивает лёгкие.", ans: "прослушивает", viet: "Bác sĩ cẩn thận khám phổi (bằng ống nghe).", why: "прослушивать = nghe bằng ống nghe (chuyên ngành y tế)." },
  { id: 4, sentence: "Он так и не дослушал оперу.", ans: "дослушал", viet: "Anh ấy đã не nghe nốt vở opera.", why: "дослушать = nghe đến cùng, nghe nốt phần còn lại." },
  { id: 5, sentence: "У неё такой красивый голос, она так поёт — заслушаешься!", ans: "заслушаешься", viet: "Cô ấy có giọng hát đẹp quá, cô ấy hát đến mức người ta mê mẩn!", why: "заслушаться = say sưa nghe, mê mẩn nghe." },
  { id: 6, sentence: "На собрании был заслушан отчёт о проделанной работе.", ans: "заслушан", viet: "Tại cuộc họp, báo cáo công việc đã được nghe.", why: "заслушать = chính thức nghe (báo cáo, diễn văn) trong hoàn cảnh trang trọng." },
  { id: 7, sentence: "Как ты смел ослушаться родителей!", ans: "ослушаться", viet: "Sao con dám cãi lời bố mẹ!", why: "ослушаться = không nghe lời, cãi lời." },
  { id: 8, sentence: "Родителей надо слушаться.", ans: "слушаться", viet: "Phải vâng lời bố mẹ.", why: "слушаться = vâng lời, phục tùng." },
  { id: 9, sentence: "Молодёжь редко слушает советы стариков.", ans: "слушает", viet: "Thanh niên hiếm khi nghe theo lời khuyên của người già.", why: "слушать = làm theo, nghe theo." },
  { id: 10, sentence: "Послушай, где моя тетрадь?", ans: "послушай", viet: "Này, nghe đây, vở của tôi đâu rồi?", why: "послушай(те) = dùng để gọi sự chú ý (Này! Nghe này!)." },
  { id: 11, sentence: "Мы прослушали курс лекций по стилистике.", ans: "прослушали", viet: "Chúng tôi đã học (nghe) một khóa bài giảng về phong cách học.", why: "прослушать курс = học/nghe trọn một khóa học." },
  { id: 12, sentence: "В суде слушали дело об ограблении магазина.", ans: "слушали", viet: "Tại tòa án người ta xét xử vụ án cướp cửa hàng.", why: "слушать дело = xét xử vụ án (trong tòa án)." },
  { id: 13, sentence: "Некрасиво подсматривать и подслушивать.", ans: "подслушивать", viet: "Nhìn trộm và nghe lén là không đẹp.", why: "подслушивать = nghe lén." },
  { id: 14, sentence: "Он прислушался к разговору за стеной, но так ничего и не услышал.", ans: "прислушался", viet: "Anh ấy dỏng tai nghe cuộc trò chuyện sau bức tường, nhưng không nghe thấy gì cả.", why: "прислушаться = dỏng tai nghe, cố gắng nghe." },
  { id: 15, sentence: "Тебе неплохо бы прислушаться к мнению старших!", ans: "прислушаться", viet: "Cháu nên lưu tâm đến ý kiến của người lớn!", why: "прислушаться к (мнению) = lưu tâm tới, để ý đến." },
  { id: 16, sentence: "Доктор прослушал грудную клетку пациента.", ans: "прослушал", viet: "Bác sĩ đã khám lồng ngực bệnh nhân (bằng ống nghe).", why: "прослушать (СВ) = khám bằng ống nghe." },
  { id: 17, sentence: "Всех участников конкурса вокалистов прослушивало авторитетное жюри.", ans: "прослушивало", viet: "Ban giám khảo uy tín đã nghe thử tất cả thí sinh cuộc thi thanh nhạc.", why: "прослушивать = nghe thử (giọng hát, khả năng) để đánh giá." },
  { id: 18, sentence: "Что ты сказал? Извини, я прослушал!", ans: "прослушал", viet: "Bạn nói gì cơ? Xin lỗi, mình nghe sót (không để ý).", why: "прослушать = mải nghĩ nên nghe sót, không nghe thấy điều người khác nói." }
];

export const slushatReplacement38 = [
  { id: 1, sentence: "Наконец, выслушай меня!", replace: "дослушай", viet: "Cuối cùng thì hãy nghe tôi nói hết!", ans: "Có thể thay được. Смысл немного изменится.", why: "«Выслушай» nhấn mạnh vào việc nghe đầy đủ một ý kiến. «Дослушай» nhấn mạnh việc nghe nốt phần cuối chưa nghe xong." },
  { id: 2, sentence: "Я хочу, чтобы ты выслушал меня.", replace: "послушал / прослушал / послушался", viet: "Tôi muốn bạn nghe tôi nói hết.", ans: "Послушал — thay được (nghe tôi nói một chút). Прослушал — thay được nhưng thay đổi nghĩa (khám bằng ống nghe). Послушался — thay đổi nghĩa hoàn toàn (vâng lời).", why: "Phụ thuộc vào từ được chọn, nghĩa và cấu trúc có thể thay đổi." },
  { id: 3, sentence: "Надо слушать старших.", replace: "слушаться / прислушиваться", viet: "Cần phải nghe lời người lớn.", ans: "Слушаться — thay được (Надо слушаться старших — vâng lời người lớn). Прислушиваться — thay được nhưng phải đổi cấu trúc (Надо прислушиваться к старшим).", why: "Прислушиваться đòi hỏi giới từ «к» + Dative." },
  { id: 4, sentence: "Нельзя слушать чужие разговоры.", replace: "подслушивать", viet: "Không được nghe lén chuyện của người khác.", ans: "Thay được. Ý nghĩa trở nên cụ thể hơn (слушать = nghe; подслушивать = cố ý nghe lén).", why: "Подслушивать có sắc thái tiêu cực rõ ràng hơn." },
  { id: 5, sentence: "Он ослушался родителей.", replace: "не послушал / не послушался", viet: "Anh ta đã cãi lời cha mẹ.", ans: "Thay được. Nghĩa gần như tương đương (không vâng lời).", why: "Cả ba đều mang ý nghĩa cãi lời, не nghe lời." },
  { id: 6, sentence: "Вслушайтесь в эти поэтические строки — какая красота в них!", replace: "Послушайте", viet: "Hãy lắng nghe kỹ những dòng thơ này — chúng thật đẹp!", ans: "Thay được, но sắc thái thay đổi và phải bỏ giới từ «в».", why: "«Вслушайтесь в эти строки» (hãy tập trung nghe kỹ vào), «Послушайте эти строки» (hãy nghe những dòng này)." },
  { id: 7, sentence: "Прислушайтесь, молодые люди, к моему совету!", replace: "Послушайте", viet: "Các bạn trẻ hãy lưu tâm đến lời khuyên của tôi!", ans: "Thay được nhưng phải thay đổi cấu trúc: «Послушайте мой совет!»", why: "Прислушайтесь к (Dative), còn Послушайте + Accusative." },
  { id: 8, sentence: "Послушайте магнитофонную запись и ответьте на несколько вопросов.", replace: "Прослушайте", viet: "Hãy nghe bản ghi âm và trả lời một vài câu hỏi.", ans: "Thay được. Смысл gần như giữ nguyên.", why: "«Прослушайте» thường được dùng trong môi trường học thuật/bài tập, mang ý nghe từ đầu đến cuối." },
  { id: 9, sentence: "Она начиталась любовных романов, наслушалась фантастических любовных историй — вот и живёт в иллюзорном мире.", replace: "слушала / прослушала", viet: "Cô ấy đọc quá nhiều tiểu thuyết ngôn tình, nghe quá nhiều chuyện tình viễn tưởng — nên mới sống trong thế giới ảo tưởng.", ans: "Слушала — thay được но mất đi sắc thái \"nghe quá nhiều đến mức ngán/bão hòa\". Прослушала — не phù hợp ngữ cảnh.", why: "Tiền tố на- mang ý nghĩa thực hiện hành động rất nhiều lần/số lượng lớn." },
  { id: 10, sentence: "Как хорошо поют — заслушаешься!", replace: "слушаешь и слушаешь / слушаешь и не наслушаешься / вслушаешься", viet: "Họ hát hay quá — nghe mà mê mẩn!", ans: "Слушаешь и слушаешь / слушаешь и не наслушаешься — thay được, giữ nguyên nghĩa say mê. Вслушаешься — thay đổi nghĩa (tập trung nghe).", why: "Заслушаешься thể hiện sự say mê, cuốn hút." }
];

export const slushatDialog39 = [
  { id: 1, prompt: "Прислушаться к чему-либо — …", ans: "— Тебе стоит прислушаться к мнению врача. — Да, наверное, он прав.", viet: "— Cậu nên lưu tâm đến ý kiến của bác sĩ. — Ừ, có lẽ ông ấy đúng.", why: "прислушаться к чему-либо = chú ý, lưu tâm đến." },
  { id: 2, prompt: "Нехорошо подслушивать что-либо — …", ans: "— Нехорошо подслушивать чужие разговоры! — Извините, я случайно услышал.", viet: "— Nghe lén chuyện của người khác là không tốt! — Xin lỗi, tôi vô tình nghe thấy thôi.", why: "подслушивать = nghe lén." },
  { id: 3, prompt: "Кого не надо слушать — …", ans: "— Кого не надо слушать в этой ситуации? — Не слушай сплетников и завистников.", viet: "— Trong tình huống này не nên nghe lời ai? — Đừng nghe những kẻ hay ngồi lê đôi mách và ghen tị.", why: "слушать кого-либо = nghe theo, nghe lời ai." },
  { id: 4, prompt: "Кого надо слушаться — …", ans: "— Кого надо слушаться детям? — Детям всегда надо слушаться родителей.", viet: "— Trẻ em cần phải vâng lời ai? — Trẻ em luôn cần vâng lời bố mẹ.", why: "слушаться кого-либо = vâng lời ai (đòi hỏi sự phục tùng)." },
  { id: 5, prompt: "Почему вы прослушали вопрос — …", ans: "— Почему вы прослушали вопрос? — Извините, я отвлёкся и не услышал.", viet: "— Tại sao anh lại nghe sót câu hỏi? — Xin lỗi, tôi bị phân tâm nên не nghe thấy.", why: "прослушать = nghe sót do lơ đãng." },
  { id: 6, prompt: "Чем можно заслушаться — …", ans: "— Чем можно заслушаться в этом лесу? — Здесь можно заслушаться пением птиц.", viet: "— Trong khu rừng này có thể say sưa nghe cái gì? — Ở đây có thể say sưa nghe tiếng chim hót.", why: "заслушаться чем-либо (Т.п.) = say sưa nghe cái gì." },
  { id: 7, prompt: "Чего он, к сожалению, наслушался — …", ans: "— Чего он, к сожалению, наслушался? — Он наслушался плохих советов от друзей.", viet: "— Thật tiếc là cậu ấy đã nghe quá nhiều điều gì? — Cậu ấy đã nghe quá nhiều lời khuyên tồi từ bạn bè.", why: "наслушаться чего-либо (Р.п.) = nghe quá nhiều điều gì đó (thường là tiêu cực)." },
  { id: 8, prompt: "Кого всегда надо выслушать — …", ans: "— Кого всегда надо выслушать до конца? — Нужно всегда выслушать своего собеседника.", viet: "— Luôn cần phải nghe ai nói cho đến cùng? — Luôn cần phải lắng nghe người đối thoại với mình.", why: "выслушать кого-либо = nghe ai đó nói từ đầu đến cuối." },
  { id: 9, prompt: "Почему парень ослушался отца — …", ans: "— Почему парень ослушался отца? — Потому что он хотел поступить по-своему.", viet: "— Tại sao chàng trai lại cãi lời cha mình? — Bởi vì cậu ấy muốn làm theo ý mình.", why: "ослушаться кого-либо = не vâng lời, cãi lời." },
  { id: 10, prompt: "Чей доклад был заслушан — …", ans: "— Чей доклад был заслушан на собрании? — На собрании был заслушан доклад директора.", viet: "— Báo cáo của ai đã được nghe tại cuộc họp? — Báo cáo của giám đốc đã được nghe.", why: "заслушать доклад = chính thức nghe báo cáo." }
];
