export const videtEx34 = [
  { id: 1, sentence: "Мы с тобой так давно не … ! (видели — виделись)", options: ["видели", "виделись"], correct: "виделись", viet: "Chúng ta lâu lắm rồi không gặp nhau!", why: "видеться = gặp nhau (lẫn nhau). видели chỉ là 'đã thấy'." },
  { id: 2, sentence: "Как много лет он не … любви! (видел — виделся)", options: ["видел", "виделся"], correct: "видел", viet: "Đã bao nhiêu năm rồi anh ấy не biết đến tình yêu!", why: "видеть любовь = trải nghiệm/chứng kiến tình yêu. видеться không dùng với tân ngữ này." },
  { id: 3, sentence: "Он так много путешествовал, многое … в своей жизни. (видел — перевидал)", options: ["видел", "перевидал"], correct: "перевидал", viet: "Anh ấy đã đi du lịch rất nhiều, chứng kiến biết bao điều trong cuộc đời.", why: "перевидал nhấn mạnh số lượng lớn kinh nghiệm đã trải qua bằng mắt." },
  { id: 4, sentence: "Ты знаешь, она может … , что произойдёт в ближайшем будущем. (предвидеть — предвидеться)", options: ["предвидеть", "предвидится"], correct: "предвидеть", viet: "Bạn biết không, cô ấy có thể lường trước được điều gì sẽ xảy ra trong tương lai gần.", why: "Chủ ngữ là она, dùng động từ chủ động. предвидится là dạng vô nhân xưng." },
  { id: 5, sentence: "Ужина не … ! (предвидится — видится)", options: ["предвидится", "видится"], correct: "предвидится", viet: "Xem ra sẽ không có bữa tối đâu!", why: "Cấu trúc vô nhân xưng chỉ sự việc không mong đợi sẽ xảy ra: не предвидится." },
  { id: 6, sentence: "Зрение резко ухудшилось, он стал совсем плохо … . (видеть — видать)", options: ["видеть", "видать"], correct: "видеть", viet: "Thị lực giảm sút rõ rệt, anh ấy bắt đầu nhìn rất kém.", why: "видеть là động từ chuẩn chỉ khả năng thị giác. видать là dạng khẩu ngữ/thông tục." },
  { id: 7, sentence: "Мы … с тобой каждый день. (видим — видимся)", options: ["видим", "видимся"], correct: "видимся", viet: "Chúng ta gặp nhau mỗi ngày.", why: "видимся = gặp gỡ lẫn nhau (động từ phản thân)." },
  { id: 8, sentence: "Как … свою ненаглядную, так сразу бежит ей навстречу. (завидит — увидит)", options: ["завидит", "увидит"], correct: "завидит", viet: "Hễ cứ thoáng thấy người yêu là anh ta chạy ngay lại đón.", why: "завидит mang sắc thái 'thoáng trông thấy từ xa'." },
  { id: 9, sentence: "Какие такие привидения? Тебе это померещилось, просто … . (увиделось — привиделось)", options: ["увиделось", "привиделось"], correct: "привиделось", viet: "Ma quỷ nào cơ? Cậu chỉ tưởng tượng ra thôi, chỉ là ảo giác thôi.", why: "привиделось = tưởng thấy, thấy trong ảo giác, mộng mị." },
  { id: 10, sentence: "Прощай! Даст Бог, когда-нибудь … . (свидимся — увидимся)", options: ["свидимся", "увидимся"], correct: "свидимся", viet: "Tạm biệt! Nếu Chúa muốn, rồi có ngày chúng ta sẽ gặp lại.", why: "свидимся thường dùng trong các lời chia tay trang trọng hoặc có sắc thái dân gian, đặc biệt đi kèm với cụm 'Даст Бог'." }
];

export const videtAnalysis33 = [
  { id: 1, sentence: "Многое он перевидал на своём веку.", ans: "перевидал", viet: "Suốt đời mình ông ấy đã chứng kiến rất nhiều chuyện.", why: "перевидать = đã thấy rất nhiều, đã trải qua rất nhiều." },
  { id: 2, sentence: "Предвижу некоторые осложнения.", ans: "предвижу", viet: "Tôi dự đoán sẽ có một vài rắc rối.", why: "предвидеть = thấy trước, lường trước, dự đoán." },
  { id: 3, sentence: "Ничего неожиданного не предвидится.", ans: "не предвидится", viet: "Không có điều gì bất ngờ được dự báo cả.", why: "не предвидится = dạng vô nhân xưng, nghĩa là 'không được dự báo, không có dấu hiệu xảy ra'." },
  { id: 4, sentence: "Он стал хуже видеть.", ans: "видеть", viet: "Anh ấy bắt đầu nhìn kém hơn (thị lực giảm).", why: "видеть = khả năng nhìn, thị lực." },
  { id: 5, sentence: "Увидев меня, он очень обрадовался.", ans: "увидев", viet: "Vừa nhìn thấy tôi, anh ấy rất vui.", why: "увидев = trạng động từ (деепричастие) của увидеть, hành động xảy ra trước: 'khi nhìn thấy'." },
  { id: 6, sentence: "Вчера я его не видел.", ans: "не видел", viet: "Hôm qua tôi không gặp/không thấy anh ấy.", why: "не видеть = не nhìn thấy, không gặp mặt." },
  { id: 7, sentence: "Хочется наконец повидаться со всеми.", ans: "повидаться", viet: "Cuối cùng cũng muốn được gặp gỡ tất cả mọi người.", why: "повидаться = gặp gỡ nhau (thường mang ý nghĩa mong mỏi, hỏi thăm)." },
  { id: 8, sentence: "Вижу, сознаю свою ошибку.", ans: "Вижу", viet: "Tôi thấy, tôi nhận thức được sai lầm của mình.", why: "видеть (nghĩa bóng) = nhận thấy, nhận thức, hiểu ra." },
  { id: 9, sentence: "Привидится же во сне такое! Надо же!", ans: "Привидится", viet: "Trong mơ mà cũng mộng thấy chuyện như vậy! Thật là!", why: "привидеться = mộng mị, tưởng tượng, thấy trong ảo giác/giấc mơ." },
  { id: 10, sentence: "Завидев хозяина, собака радостно залаяла.", ans: "Завидев", viet: "Vừa thoáng thấy chủ, chú chó đã sủa lên mừng rỡ.", why: "завидев = trạng động từ của завидеть, mang nghĩa 'thoáng thấy từ xa'." }
];

export const videtDialog35 = [
  { id: 1, prompt: "Можно ли предвидеть какие-либо неприятности — …", ans: "— Можно ли предвидеть какие-либо неприятности? — Да, если внимательно изучить все обстоятельства дела.", viet: "— Liệu có thể lường trước được những rắc rối nào không? — Có, nếu nghiên cứu kỹ lưỡng mọi tình huống của sự việc.", why: "предвидеть = lường trước, đoán trước." },
  { id: 2, prompt: "Чего не предвидится в ближайшее время — …", ans: "— Чего не предвидится в ближайшее время? — К сожалению, повышения зарплаты пока не предвидится.", viet: "— Điều gì sẽ не được dự kiến xảy ra trong thời gian tới? — Đáng tiếc là việc tăng lương hiện tại vẫn chưa có dấu hiệu xảy ra.", why: "не предвидится = không được mong đợi/dự kiến xảy ra." },
  { id: 3, prompt: "Вы хорошо видите — …", ans: "— Вы хорошо видите этот текст издали? — Нет, мне нужны очки, я стал хуже видеть.", viet: "— Bạn có nhìn rõ đoạn văn bản này từ xa không? — Không, tôi cần kính, dạo này tôi nhìn kém hơn rồi.", why: "видеть = khả năng nhìn bằng mắt." },
  { id: 4, prompt: "Что или кого хочется увидеть (повидать) — …", ans: "— Кого тебе хочется повидать после возвращения? — Больше всего мне хочется повидать старых школьных друзей.", viet: "— Bạn muốn gặp ai sau khi trở về? — Hơn hết là tôi muốn gặp gỡ lại những người bạn học cũ.", why: "повидать = gặp gỡ, gặp lại ai đó." },
  { id: 5, prompt: "Что или кого вы боитесь увидеть — …", ans: "— Кого вы боитесь увидеть на этой встрече? — Я боюсь увидеть своего бывшего начальника.", viet: "— Bạn sợ gặp ai ở buổi gặp mặt này? — Tôi sợ giáp mặt người sếp cũ của mình.", why: "увидеть = nhìn thấy, gặp mặt." },
  { id: 6, prompt: "С кем обязательно надо увидеться (повидаться) — …", ans: "— С кем обязательно надо увидеться на выходных? — Обязательно надо повидаться с бабушкой, она давно нас ждёт.", viet: "— Cuối tuần nhất định phải gặp ai? — Nhất định phải qua thăm bà, bà chờ chúng ta lâu rồi.", why: "повидаться с кем-либо = gặp gỡ, thăm hỏi ai." },
  { id: 7, prompt: "Что мы видим, проводя это исследование — …", ans: "— Что мы видим, проводя это исследование? — Мы видим, что уровень загрязнения воды значительно снизился.", viet: "— Chúng ta nhận thấy điều gì khi tiến hành nghiên cứu này? — Chúng ta nhận thấy mức độ ô nhiễm nước đã giảm đáng kể.", why: "видеть (nghĩa bóng) = nhận thấy, hiểu được từ số liệu/kết quả." },
  { id: 8, prompt: "Почему он так кричит? Может, ему что-то привиделось в темноте — …", ans: "— Почему он так кричит? Может, ему что-то привиделось в темноте? — Наверное, ему привиделось привидение из-за страшного фильма.", viet: "— Tại sao cậu ấy lại hét lên thế? Có phải cậu ấy thấy ảo giác gì trong bóng tối không? — Chắc cậu ấy mường tượng ra ma quỷ vì bộ phim kinh dị lúc nãy.", why: "привидеться = mường tượng, nhìn thấy ảo giác/ma quỷ." }
];
